export interface OpenDemand {
  dem_id: string;
  dem_ctoolnumber: string;
  dem_ctooldate: string;
  dem_cmm_id: string;
  dem_clm_id: string;
  dem_lcm_id: string;
  location_details: any;
  client_details: any;
  dem_validtill: string;
  dem_skillset: string;
  dem_lob_id: string;
  dem_idm_id: string;
  dem_dsm_id: [null],
  dem_positions: string;
  dem_rrnumber: string;
  dem_jrnumber: string;
  dem_rrgade: string;
  dem_gcblevel: string;
  dem_jd: string;
  dem_comment: string;
  dem_isreopened: string;
  dem_isactive: string;
  dem_insertby: string;
  dem_updateby: string;
  dem_insertdate: string;
  dem_updatedate: string;
  lob_details: any;
  dem_position_name: any;
  status_details: any;
  }